### ISSUE TITLE
Items (Cats) pages back

### ISSUE THREAD

**Issue by ocardinaux** [ocardinaux/thp_next_kitten_project#3]
**WHY**

All sold cats should be available to display

**TODO**

* [ ] `cats` db and model
* [ ] seed for cats without image

**Comment by ocardinaux** [comment]
@TheMindset, I merged and closed trop vite, there was a seed to do in this issue too, my bad 🤔

**Comment by ocardinaux** [comment]
Wrong issue, I reopen it...

**Comment by TheMindset** [comment]
The images will be integrate with Active Storage
